sensor_topic:
    lidar_topic: "/rslidar_points"
    imu_topic: "/IMU_data"

slam_mode: 2  # 1: Mapping, 2: Localization

lidar:
    # Velodyne_16, Velodyne_32, Velodyne_64, Ouster_128_os1,
    # LeiShen_16, RoboSense_16, Livox_Avia, Livox_Mid_360, None
    lidar_sensor_type: None
    lidar_point_jump_span: 1
    lidar_point_time_scale: 1.0
    lidar_use_min_distance: 2.0
    lidar_use_max_distance: 150.0
    lidar_rotation_noise_std: 0.001
    lidar_position_noise_std: 0.01

    # if lidar_sensor_type is equal to None, need set below parameters
    lidar_scan: 16
    lidar_lower_angle: 15.0 # degree
    lidar_horizon_scan: 1800
    lidar_vertical_resolution: 2.0 # degree

imu:
    init_acc_bias: 0.0
    init_gyro_bias: 0.0
    acc_noise_std: 0.1
    gyro_noise_std: 0.01
    acc_rw_noise_std: 1.0e-5
    gyro_rw_noise_std: 1.0e-5
    has_orientation: true
    data_searcher_buffer_size: 5000

gravity: 9.81

calibration:
    lidar_to_imu: [ 1.0, 0.0, 0.0, 0.0,
                    0.0, 1.0, 0.0, 0.0,
                    0.0, 0.0, 1.0, 0.0,
                    0.0, 0.0, 0.0, 1.0 ]

frontend:
    fusion_opti_iters: 10
    fusion_method: TightCouplingOptimization # LooseCoupling, TightCouplingKF, TightCouplingOptimization

    registration_and_searcher_mode: PointToPlane_IVOX
    feature:
        planar_voxel_filter_size: 0.5
    registration:
        optimization_iter_num: 10
        point_to_planar_thres: 0.1
        position_converge_thres: 0.01
        rotation_converge_thres: 0.01

loopclosure:
    registration_converge_threshold: 1.5
    skip_near_loopclosure_threshold: 100
    skip_near_keyframe_threshold: 100
    candidate_local_map_left_range: 20
    candidate_local_map_right_range: 20
    loopclosure_local_map_left_range: 30
    near_neighbor_distance_threshold: 10.0
